// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Bradaz.Clarizen.API.Models.DescribeEntityJsonTypes;

namespace Bradaz.Clarizen.API.Models.DescribeEntityJsonTypes
{

    public class Field
    {

        [JsonProperty("referencedEntities")]
        public string[] ReferencedEntities { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("presentationType")]
        public string PresentationType { get; set; }

        [JsonProperty("label")]
        public string Label { get; set; }

        [JsonProperty("defaultValue")]
        public object DefaultValue { get; set; }

        [JsonProperty("system")]
        public bool System { get; set; }

        [JsonProperty("calculated")]
        public bool Calculated { get; set; }

        [JsonProperty("nullable")]
        public bool Nullable { get; set; }

        [JsonProperty("createOnly")]
        public bool CreateOnly { get; set; }

        [JsonProperty("updateable")]
        public bool Updateable { get; set; }

        [JsonProperty("internal")]
        public bool Internal { get; set; }

        [JsonProperty("custom")]
        public bool Custom { get; set; }

        [JsonProperty("visible")]
        public bool Visible { get; set; }

        [JsonProperty("decimalPlaces")]
        public int DecimalPlaces { get; set; }

        [JsonProperty("filterable")]
        public bool Filterable { get; set; }

        [JsonProperty("sortable")]
        public bool Sortable { get; set; }

        [JsonProperty("_type")]
        public string _Type { get; set; }

        [JsonProperty("maxLength")]
        public int? MaxLength { get; set; }
    }

    public class EntityDescription
    {

        [JsonProperty("typeName")]
        public string TypeName { get; set; }

        [JsonProperty("fields")]
        public Field[] Fields { get; set; }

        [JsonProperty("validStates")]
        public string[] ValidStates { get; set; }

        [JsonProperty("label")]
        public string Label { get; set; }

        [JsonProperty("labelPlural")]
        public string LabelPlural { get; set; }

        [JsonProperty("parentEntity")]
        public string ParentEntity { get; set; }

        [JsonProperty("displayField")]
        public string DisplayField { get; set; }
    }

}

namespace Bradaz.Clarizen.API.Models
{

    public class DescribeEntity
    {

        [JsonProperty("entityDescriptions")]
        public EntityDescription[] EntityDescriptions { get; set; }
    }

}
