// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Clarizen.Net.DataAccessLayer.Models
{

    public partial class Bug  : ClarizenEntity
    { /*Root*/

        [JsonProperty("CreatedBy")]
        public string CreatedBy { get; set; }

        [JsonProperty("CreatedOn")]
        public DateTime CreatedOn { get; set; }

        [JsonProperty("LastUpdatedBy")]
        public string LastUpdatedBy { get; set; }

        [JsonProperty("LastUpdatedOn")]
        public DateTime LastUpdatedOn { get; set; }

        [JsonProperty("SYSID")]
        public string SYSID { get; set; }

        [JsonProperty("ExternalID")]
        public string ExternalID { get; set; }

        [JsonProperty("PercentCompleted")]
        public double PercentCompleted { get; set; }

        [JsonProperty("AttachmentsCount")]
        public int AttachmentsCount { get; set; }

        [JsonProperty("PostsCount")]
        public int PostsCount { get; set; }

        [JsonProperty("NotesCount")]
        public int NotesCount { get; set; }

        [JsonProperty("Title")]
        public string Title { get; set; }

        [JsonProperty("Severity")]
        public string Severity { get; set; }

        [JsonProperty("Priority")]
        public int Priority { get; set; }

        [JsonProperty("Mandatory")]
        public bool Mandatory { get; set; }

        [JsonProperty("Owner")]
        public string Owner { get; set; }

        [JsonProperty("DueDate")]
        public DateTime DueDate { get; set; }

        [JsonProperty("AssignedTo")]
        public string AssignedTo { get; set; }

        [JsonProperty("AssignmentDate")]
        public DateTime AssignmentDate { get; set; }

        [JsonProperty("SubmittedBy")]
        public string SubmittedBy { get; set; }

        [JsonProperty("SubmissionDate")]
        public DateTime SubmissionDate { get; set; }

        [JsonProperty("EvaluatedBy")]
        public string EvaluatedBy { get; set; }

        [JsonProperty("EvaluationDate")]
        public DateTime EvaluationDate { get; set; }

        [JsonProperty("OpenedBy")]
        public string OpenedBy { get; set; }

        [JsonProperty("OpeningDate")]
        public DateTime OpeningDate { get; set; }

        [JsonProperty("ResolvedBy")]
        public string ResolvedBy { get; set; }

        [JsonProperty("ResolvedDate")]
        public DateTime ResolvedDate { get; set; }

        [JsonProperty("ResolutionDetails")]
        public string ResolutionDetails { get; set; }

        [JsonProperty("ClosedBy")]
        public string ClosedBy { get; set; }

        [JsonProperty("ClosureDate")]
        public DateTime ClosureDate { get; set; }

        [JsonProperty("RejectedBy")]
        public string RejectedBy { get; set; }

        [JsonProperty("RejectionDate")]
        public DateTime RejectionDate { get; set; }

        [JsonProperty("RejectDetails")]
        public string RejectDetails { get; set; }

        [JsonProperty("ReopenedBy")]
        public string ReopenedBy { get; set; }

        [JsonProperty("ReopeningDate")]
        public DateTime ReopeningDate { get; set; }

        [JsonProperty("ReopenReasons")]
        public string ReopenReasons { get; set; }

        [JsonProperty("DeferredBy")]
        public string DeferredBy { get; set; }

        [JsonProperty("DeferringDate")]
        public DateTime DeferringDate { get; set; }

        [JsonProperty("Comment")]
        public string Comment { get; set; }

        [JsonProperty("PlannedFor")]
        public string PlannedFor { get; set; }

        [JsonProperty("ReportedbyCustomer")]
        public bool ReportedbyCustomer { get; set; }

        [JsonProperty("Category")]
        public string Category { get; set; }

        [JsonProperty("DuplicateTo")]
        public string DuplicateTo { get; set; }

        [JsonProperty("Description")]
        public string Description { get; set; }

        [JsonProperty("PlainText")]
        public string PlainText { get; set; }

        [JsonProperty("LastUpdatedBySystemOn")]
        public DateTime LastUpdatedBySystemOn { get; set; }

        [JsonProperty("DeferReasons")]
        public string DeferReasons { get; set; }

        [JsonProperty("Work")]
        public Work Work { get; set; }

        [JsonProperty("ActualEffort")]
        public ActualEffort ActualEffort { get; set; }

        [JsonProperty("RemainingEffort")]
        public RemainingEffort RemainingEffort { get; set; }

        [JsonProperty("WorkManuallySet")]
        public bool WorkManuallySet { get; set; }

        [JsonProperty("RemainingEffortManuallySet")]
        public bool RemainingEffortManuallySet { get; set; }

        [JsonProperty("WorkVariance")]
        public WorkVariance WorkVariance { get; set; }

        [JsonProperty("EmailsCount")]
        public int EmailsCount { get; set; }

        [JsonProperty("Justification")]
        public string Justification { get; set; }

        [JsonProperty("BusinessAlignment")]
        public string BusinessAlignment { get; set; }

        [JsonProperty("PlannedSavings")]
        public string PlannedSavings { get; set; }

        [JsonProperty("ExpectedBusinessValue")]
        public string ExpectedBusinessValue { get; set; }

        [JsonProperty("GoalsAchieved")]
        public bool GoalsAchieved { get; set; }

        [JsonProperty("ExpectedROI")]
        public double ExpectedROI { get; set; }

        [JsonProperty("BusinessImpact")]
        public string BusinessImpact { get; set; }

        [JsonProperty("Score")]
        public double Score { get; set; }

        [JsonProperty("OriginatedFrom")]
        public string OriginatedFrom { get; set; }

        [JsonProperty("ObjectAlias")]
        public string ObjectAlias { get; set; }

        [JsonProperty("State")]
        public string State { get; set; }

        [JsonProperty("EntityType")]
        public string EntityType { get; set; }

        [JsonProperty("ReportedBy")]
        public string ReportedBy { get; set; }

        [JsonProperty("ReportedByMail")]
        public string ReportedByMail { get; set; }

        [JsonProperty("LikesCount")]
        public int LikesCount { get; set; }

        [JsonProperty("Regression")]
        public bool Regression { get; set; }

        [JsonProperty("ImpactArea")]
        public string ImpactArea { get; set; }

        [JsonProperty("FoundInBuild")]
        public string FoundInBuild { get; set; }

        [JsonProperty("IntegratedInBuild")]
        public string IntegratedInBuild { get; set; }

        [JsonProperty("ClosedInBuild")]
        public string ClosedInBuild { get; set; }

        [JsonProperty("ReopenedInBuild")]
        public string ReopenedInBuild { get; set; }

        [JsonProperty("SfExternalId")]
        public string SfExternalId { get; set; }

        [JsonProperty("SfExternalName")]
        public string SfExternalName { get; set; }

        [JsonProperty("ZdExternalId")]
        public string ZdExternalId { get; set; }

        [JsonProperty("ZdExternalName")]
        public string ZdExternalName { get; set; }
    }

}
