// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Clarizen.Net.DataAccessLayer.Models
{

    public partial class Document  : ClarizenEntity
    { /*Root*/

        [JsonProperty("CreatedBy")]
        public string CreatedBy { get; set; }

        [JsonProperty("CreatedOn")]
        public DateTime CreatedOn { get; set; }

        [JsonProperty("LastUpdatedBy")]
        public string LastUpdatedBy { get; set; }

        [JsonProperty("LastUpdatedOn")]
        public DateTime LastUpdatedOn { get; set; }

        [JsonProperty("ExternalID")]
        public string ExternalID { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Description")]
        public string Description { get; set; }

        [JsonProperty("StorageType")]
        public string StorageType { get; set; }

        [JsonProperty("FileType")]
        public string FileType { get; set; }

        [JsonProperty("DocumentType")]
        public string DocumentType { get; set; }

        [JsonProperty("LastUpdatedBySystemOn")]
        public DateTime LastUpdatedBySystemOn { get; set; }

        [JsonProperty("SYSID")]
        public string SYSID { get; set; }

        [JsonProperty("EntityType")]
        public string EntityType { get; set; }

        [JsonProperty("ViewerUrl")]
        public string ViewerUrl { get; set; }

        [JsonProperty("FileModificationDate")]
        public DateTime FileModificationDate { get; set; }

        [JsonProperty("LikesCount")]
        public int LikesCount { get; set; }

        [JsonProperty("ProofDecision")]
        public string ProofDecision { get; set; }

        [JsonProperty("Content")]
        public string Content { get; set; }

        [JsonProperty("ContentLength")]
        public int ContentLength { get; set; }

        [JsonProperty("IsBeingProofed")]
        public bool IsBeingProofed { get; set; }

        [JsonProperty("Url")]
        public string Url { get; set; }

        [JsonProperty("ProofLastUpdatedOn")]
        public DateTime ProofLastUpdatedOn { get; set; }

        [JsonProperty("ProofOwner")]
        public string ProofOwner { get; set; }

        [JsonProperty("ProofUpdateCompletedOn")]
        public DateTime ProofUpdateCompletedOn { get; set; }

        [JsonProperty("LastDecisionBy")]
        public string LastDecisionBy { get; set; }

        [JsonProperty("LastDecisionByEmail")]
        public string LastDecisionByEmail { get; set; }

        [JsonProperty("LastApproverDecision")]
        public string LastApproverDecision { get; set; }
    }

}
