// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Clarizen.Net.DataAccessLayer.Models
{

    public partial class ExpenseSheet  : ClarizenEntity
    { /*Root*/

        [JsonProperty("CreatedBy")]
        public string CreatedBy { get; set; }

        [JsonProperty("CreatedOn")]
        public DateTime CreatedOn { get; set; }

        [JsonProperty("LastUpdatedBy")]
        public string LastUpdatedBy { get; set; }

        [JsonProperty("LastUpdatedOn")]
        public DateTime LastUpdatedOn { get; set; }

        [JsonProperty("Description")]
        public string Description { get; set; }

        [JsonProperty("SYSID")]
        public string SYSID { get; set; }

        [JsonProperty("Owner")]
        public string Owner { get; set; }

        [JsonProperty("ApprovedBy")]
        public string ApprovedBy { get; set; }

        [JsonProperty("ApprovalDate")]
        public DateTime ApprovalDate { get; set; }

        [JsonProperty("Project")]
        public string Project { get; set; }

        [JsonProperty("PostsCount")]
        public int PostsCount { get; set; }

        [JsonProperty("Date")]
        public DateTime Date { get; set; }

        [JsonProperty("Total")]
        public Total Total { get; set; }

        [JsonProperty("ReimbursedTotal")]
        public ReimbursedTotal ReimbursedTotal { get; set; }

        [JsonProperty("BillableTotal")]
        public BillableTotal BillableTotal { get; set; }

        [JsonProperty("SubmittedOn")]
        public DateTime SubmittedOn { get; set; }

        [JsonProperty("Approver")]
        public string Approver { get; set; }

        [JsonProperty("LastUpdatedBySystemOn")]
        public DateTime LastUpdatedBySystemOn { get; set; }

        [JsonProperty("AttachmentsCount")]
        public int AttachmentsCount { get; set; }

        [JsonProperty("ExternalID")]
        public string ExternalID { get; set; }

        [JsonProperty("LikesCount")]
        public int LikesCount { get; set; }

        [JsonProperty("EntityType")]
        public string EntityType { get; set; }

        [JsonProperty("State")]
        public string State { get; set; }
    }

}
