// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Clarizen.Net.DataAccessLayer.Models
{

    public  class CostRegularRate 
    { /*Root*/

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("value")]
        public double Value { get; set; }
    }

    public  class CostOvertimeRate 
    { /*Root*/

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("value")]
        public double Value { get; set; }
    }

    public  class RevenueRegularRate 
    { /*Root*/

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("value")]
        public double Value { get; set; }
    }

    public  class RevenueOvertimeRate 
    { /*Root*/

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("value")]
        public double Value { get; set; }
    }

    public partial class Organization  : ClarizenEntity
    { /*Root*/

        [JsonProperty("CreatedBy")]
        public string CreatedBy { get; set; }

        [JsonProperty("CreatedOn")]
        public DateTime CreatedOn { get; set; }

        [JsonProperty("LastUpdatedBy")]
        public string LastUpdatedBy { get; set; }

        [JsonProperty("LastUpdatedOn")]
        public DateTime LastUpdatedOn { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Description")]
        public string Description { get; set; }

        [JsonProperty("ExternalID")]
        public string ExternalID { get; set; }

        [JsonProperty("State")]
        public string State { get; set; }

        [JsonProperty("Country")]
        public string Country { get; set; }

        [JsonProperty("TimeZone")]
        public string TimeZone { get; set; }

        [JsonProperty("CountryState")]
        public string CountryState { get; set; }

        [JsonProperty("DefaultCurrency")]
        public string DefaultCurrency { get; set; }

        [JsonProperty("Language")]
        public string Language { get; set; }

        [JsonProperty("LastUpdatedBySystemOn")]
        public DateTime LastUpdatedBySystemOn { get; set; }

        [JsonProperty("Domain")]
        public string Domain { get; set; }

        [JsonProperty("SupportUser")]
        public string SupportUser { get; set; }

        [JsonProperty("EntityType")]
        public string EntityType { get; set; }

        [JsonProperty("Package")]
        public string Package { get; set; }

        [JsonProperty("UpdateRequestsCounter")]
        public long UpdateRequestsCounter { get; set; }

        [JsonProperty("CostRegularRate")]
        public CostRegularRate CostRegularRate { get; set; }

        [JsonProperty("CostOvertimeRate")]
        public CostOvertimeRate CostOvertimeRate { get; set; }

        [JsonProperty("RevenueRegularRate")]
        public RevenueRegularRate RevenueRegularRate { get; set; }

        [JsonProperty("RevenueOvertimeRate")]
        public RevenueOvertimeRate RevenueOvertimeRate { get; set; }

        [JsonProperty("CustomCss")]
        public string CustomCss { get; set; }

        [JsonProperty("ImageUrl")]
        public string ImageUrl { get; set; }

        [JsonProperty("CustomIcon")]
        public string CustomIcon { get; set; }

        [JsonProperty("Profile")]
        public string Profile { get; set; }
    }

}
