// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Clarizen.Net.DataAccessLayer.Models
{

    public  class RegularRate 
    { /*Root*/

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("value")]
        public double Value { get; set; }
    }

    public  class OvertimeRate 
    { /*Root*/

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("value")]
        public double Value { get; set; }
    }

    public partial class Rate  : ClarizenEntity
    { /*Root*/

        [JsonProperty("CreatedBy")]
        public string CreatedBy { get; set; }

        [JsonProperty("CreatedOn")]
        public DateTime CreatedOn { get; set; }

        [JsonProperty("LastUpdatedBy")]
        public string LastUpdatedBy { get; set; }

        [JsonProperty("LastUpdatedOn")]
        public DateTime LastUpdatedOn { get; set; }

        [JsonProperty("ExternalID")]
        public string ExternalID { get; set; }

        [JsonProperty("RateFor")]
        public string RateFor { get; set; }

        [JsonProperty("RateType")]
        public string RateType { get; set; }

        [JsonProperty("EffectiveFrom")]
        public DateTime EffectiveFrom { get; set; }

        [JsonProperty("EffectiveTo")]
        public DateTime EffectiveTo { get; set; }

        [JsonProperty("RegularRate")]
        public RegularRate RegularRate { get; set; }

        [JsonProperty("OvertimeRate")]
        public OvertimeRate OvertimeRate { get; set; }

        [JsonProperty("LastUpdatedBySystemOn")]
        public DateTime LastUpdatedBySystemOn { get; set; }

        [JsonProperty("EntityType")]
        public string EntityType { get; set; }
    }

}
