// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Clarizen.Net.DataAccessLayer.Models
{

    public  class Duration 
    { /*Root*/

        [JsonProperty("unit")]
        public string Unit { get; set; }

        [JsonProperty("value")]
        public double Value { get; set; }
    }

    public  class BillingRate 
    { /*Root*/

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("value")]
        public double Value { get; set; }
    }

    public  class Cost 
    { /*Root*/

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("value")]
        public double Value { get; set; }
    }

    public  class CostRate 
    { /*Root*/

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("value")]
        public double Value { get; set; }
    }

    public  class Price 
    { /*Root*/

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("value")]
        public double Value { get; set; }
    }

    public partial class Timesheet  : ClarizenEntity
    { /*Root*/

        [JsonProperty("CreatedBy")]
        public string CreatedBy { get; set; }

        [JsonProperty("CreatedOn")]
        public DateTime CreatedOn { get; set; }

        [JsonProperty("LastUpdatedBy")]
        public string LastUpdatedBy { get; set; }

        [JsonProperty("LastUpdatedOn")]
        public DateTime LastUpdatedOn { get; set; }

        [JsonProperty("ExternalID")]
        public string ExternalID { get; set; }

        [JsonProperty("State")]
        public string State { get; set; }

        [JsonProperty("ApprovedBy")]
        public string ApprovedBy { get; set; }

        [JsonProperty("ApprovalDate")]
        public DateTime ApprovalDate { get; set; }

        [JsonProperty("ReportedBy")]
        public string ReportedBy { get; set; }

        [JsonProperty("ReportedDate")]
        public DateTime ReportedDate { get; set; }

        [JsonProperty("Duration")]
        public Duration Duration { get; set; }

        [JsonProperty("RegularHours")]
        public bool RegularHours { get; set; }

        [JsonProperty("Comment")]
        public string Comment { get; set; }

        [JsonProperty("BillingRate")]
        public BillingRate BillingRate { get; set; }

        [JsonProperty("Cost")]
        public Cost Cost { get; set; }

        [JsonProperty("WorkItem")]
        public string WorkItem { get; set; }

        [JsonProperty("CostRate")]
        public CostRate CostRate { get; set; }

        [JsonProperty("Price")]
        public Price Price { get; set; }

        [JsonProperty("LastUpdatedBySystemOn")]
        public DateTime LastUpdatedBySystemOn { get; set; }

        [JsonProperty("Charged")]
        public bool Charged { get; set; }

        [JsonProperty("EntityType")]
        public string EntityType { get; set; }

        [JsonProperty("CreatorType")]
        public string CreatorType { get; set; }

        [JsonProperty("HumanResource")]
        public string HumanResource { get; set; }

        [JsonProperty("Overtime")]
        public bool Overtime { get; set; }

        [JsonProperty("AssignedApprover")]
        public string AssignedApprover { get; set; }

        [JsonProperty("DisableReportingTimeLimit")]
        public bool DisableReportingTimeLimit { get; set; }

        [JsonProperty("Project")]
        public string Project { get; set; }
    }

}
