// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Clarizen.Net.DataAccessLayer.Models
{

    public  class CostRegularRate 
    { /*Root*/

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("value")]
        public double Value { get; set; }
    }

    public  class CostOvertimeRate 
    { /*Root*/

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("value")]
        public double Value { get; set; }
    }

    public  class RevenueRegularRate 
    { /*Root*/

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("value")]
        public double Value { get; set; }
    }

    public  class RevenueOvertimeRate 
    { /*Root*/

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("value")]
        public double Value { get; set; }
    }

    public partial class User  : ClarizenEntity
    { /*Root*/

        [JsonProperty("CreatedBy")]
        public string CreatedBy { get; set; }

        [JsonProperty("CreatedOn")]
        public DateTime CreatedOn { get; set; }

        [JsonProperty("LastUpdatedBy")]
        public string LastUpdatedBy { get; set; }

        [JsonProperty("LastUpdatedOn")]
        public DateTime LastUpdatedOn { get; set; }

        [JsonProperty("DisplayName")]
        public string DisplayName { get; set; }

        [JsonProperty("ExternalID")]
        public string ExternalID { get; set; }

        [JsonProperty("LastUpdatedBySystemOn")]
        public DateTime LastUpdatedBySystemOn { get; set; }

        [JsonProperty("State")]
        public string State { get; set; }

        [JsonProperty("Phase")]
        public string Phase { get; set; }

        [JsonProperty("Availability")]
        public double Availability { get; set; }

        [JsonProperty("EntityType")]
        public string EntityType { get; set; }

        [JsonProperty("AttachmentsCount")]
        public int AttachmentsCount { get; set; }

        [JsonProperty("OfficeFax")]
        public string OfficeFax { get; set; }

        [JsonProperty("BusinessAddress")]
        public string BusinessAddress { get; set; }

        [JsonProperty("HomeAddress")]
        public string HomeAddress { get; set; }

        [JsonProperty("Region")]
        public string Region { get; set; }

        [JsonProperty("UserName")]
        public string UserName { get; set; }

        [JsonProperty("LastLogin")]
        public DateTime LastLogin { get; set; }

        [JsonProperty("Admin")]
        public bool Admin { get; set; }

        [JsonProperty("TimeZone")]
        public string TimeZone { get; set; }

        [JsonProperty("ExternalUser")]
        public bool ExternalUser { get; set; }

        [JsonProperty("DirectManager")]
        public string DirectManager { get; set; }

        [JsonProperty("AllowEmails")]
        public bool AllowEmails { get; set; }

        [JsonProperty("SendInvitationMail")]
        public bool SendInvitationMail { get; set; }

        [JsonProperty("Position")]
        public string Position { get; set; }

        [JsonProperty("SubscribeToProjectNotifications")]
        public bool SubscribeToProjectNotifications { get; set; }

        [JsonProperty("Language")]
        public string Language { get; set; }

        [JsonProperty("JobTitle")]
        public string JobTitle { get; set; }

        [JsonProperty("SuperUser")]
        public bool SuperUser { get; set; }

        [JsonProperty("Financial")]
        public bool Financial { get; set; }

        [JsonProperty("Location")]
        public string Location { get; set; }

        [JsonProperty("TwitterUserName")]
        public string TwitterUserName { get; set; }

        [JsonProperty("InternalId")]
        public string InternalId { get; set; }

        [JsonProperty("TwitterLastMessageId")]
        public string TwitterLastMessageId { get; set; }

        [JsonProperty("GoogleUserName")]
        public string GoogleUserName { get; set; }

        [JsonProperty("FirstName")]
        public string FirstName { get; set; }

        [JsonProperty("Signature")]
        public string Signature { get; set; }

        [JsonProperty("LastName")]
        public string LastName { get; set; }

        [JsonProperty("Email")]
        public string Email { get; set; }

        [JsonProperty("OfficePhone")]
        public string OfficePhone { get; set; }

        [JsonProperty("MobilePhone")]
        public string MobilePhone { get; set; }

        [JsonProperty("LicenseType")]
        public string LicenseType { get; set; }

        [JsonProperty("CostRegularRate")]
        public CostRegularRate CostRegularRate { get; set; }

        [JsonProperty("CostOvertimeRate")]
        public CostOvertimeRate CostOvertimeRate { get; set; }

        [JsonProperty("RevenueRegularRate")]
        public RevenueRegularRate RevenueRegularRate { get; set; }

        [JsonProperty("RevenueOvertimeRate")]
        public RevenueOvertimeRate RevenueOvertimeRate { get; set; }

        [JsonProperty("Trial")]
        public bool Trial { get; set; }

        [JsonProperty("ExpirationDate")]
        public DateTime ExpirationDate { get; set; }

        [JsonProperty("LastLoginIPAddress")]
        public string LastLoginIPAddress { get; set; }

        [JsonProperty("StopwatchesCount")]
        public int StopwatchesCount { get; set; }

        [JsonProperty("EmailNotifications")]
        public string EmailNotifications { get; set; }

        [JsonProperty("ImageUrl")]
        public string ImageUrl { get; set; }

        [JsonProperty("Profile")]
        public string Profile { get; set; }

        [JsonProperty("NotesCount")]
        public int NotesCount { get; set; }
    }

}
